version: "3.8"
services:
  app:
    build: .
    image: redis-app
    ports: ["8080:8080"]
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on: [redis]
    networks: [app-network]
    restart: always
  redis:
    image: redis:latest
    ports: ["6379:6379"]
    networks: [app-network]
    restart: always
networks:
  app-network:
    driver: bridge   